name: Build doc
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ closed ]
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: test
        description: test

jobs:
  deploy:
    name: Deploy doc to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Log
        run: |
          ls -l ./build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build