name: Build doc
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ closed ]
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: test
        description: test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: doc
          git-user: basile-parent
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages