name: NPM publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: test
        description: test

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: npm install, build, and test
        run: |
          npm install
          npm run lint
          npm run test
          npm run build
        env:
          CI: true

  build-and-publish-npm:
    if: success()
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Authenticate with NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: npm publish
        run: |
          npm install
          npm publish
        env:
          CI: true
